language: python
matrix:
  include:
    - python: "3.8"
      dist: xenial
      sudo: true
cache: pip
install:
  - pip install -r ./app/requirements.txt
script:
  - python -m pytest --cov-report term-missing --cov=./app
  - bash <(curl -s https://codecov.io/bash)
