global:
  scrape_interval: 5s

  external_labels:
    monitor: "exponea_api"

scrape_configs:
  - job_name: "prometheus"

    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "api"

    static_configs:
      - targets: ["localhost:80"]

    dns_sd_configs:
      - names: ["api"]
        port: 80
        type: A
        refresh_interval: 5s

  - job_name: grafana
    scheme: http
    static_configs:
      - targets: [localhost:3000, grafana:3000]
